// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PMSWebApi.Data;

namespace PMSWebApi.Migrations
{
    [DbContext(typeof(PMSWebApiContext))]
    [Migration("20210515193109_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PMSWebApi.DTOEntities.ProjectDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FinishDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("PMSWebApi.DTOEntities.SubProjectDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FinishDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProjectDTOId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectDTOId");

                    b.ToTable("SubProjects");
                });

            modelBuilder.Entity("PMSWebApi.DTOEntities.SubTaskDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FinishDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<int?>("TaskDTOId")
                        .HasColumnType("int");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TaskDTOId");

                    b.ToTable("SubTasks");
                });

            modelBuilder.Entity("PMSWebApi.DTOEntities.TaskDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FinishDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProjectDTOId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<int?>("SubProjectDTOId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectDTOId");

                    b.HasIndex("SubProjectDTOId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("PMSWebApi.DTOEntities.SubProjectDTO", b =>
                {
                    b.HasOne("PMSWebApi.DTOEntities.ProjectDTO", null)
                        .WithMany("SubProjects")
                        .HasForeignKey("ProjectDTOId");
                });

            modelBuilder.Entity("PMSWebApi.DTOEntities.SubTaskDTO", b =>
                {
                    b.HasOne("PMSWebApi.DTOEntities.TaskDTO", null)
                        .WithMany("SubTasks")
                        .HasForeignKey("TaskDTOId");
                });

            modelBuilder.Entity("PMSWebApi.DTOEntities.TaskDTO", b =>
                {
                    b.HasOne("PMSWebApi.DTOEntities.ProjectDTO", null)
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectDTOId");

                    b.HasOne("PMSWebApi.DTOEntities.SubProjectDTO", null)
                        .WithMany("Tasks")
                        .HasForeignKey("SubProjectDTOId");
                });

            modelBuilder.Entity("PMSWebApi.DTOEntities.ProjectDTO", b =>
                {
                    b.Navigation("SubProjects");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("PMSWebApi.DTOEntities.SubProjectDTO", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("PMSWebApi.DTOEntities.TaskDTO", b =>
                {
                    b.Navigation("SubTasks");
                });
#pragma warning restore 612, 618
        }
    }
}
